Issue/28 add course crawler
HPI-de/hpi-cloud pull request #34
Opened 2019-10-05 18:00 UTC by ShirleyNekoDev

**Fixes: #28 **

**Checklist**

- [x] Commit messages follow conventionalcommits.org
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Changes**

- small fixes in common and news-crawler
- added initial course-crawler

2019-10-05 18:02 UTC, ShirleyNekoDev commented
Todo:
- [ ] write to database
- [ ] crawling TeleTask links
- [ ] implement archive crawling

2019-10-06 18:04 UTC, JonasWanke requested changes

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/CourseSeries.kt
> +                .split(" / ")
Spaces should be removed to catch more erroneous input as the parts are trimmed anyway.

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/CourseSeries.kt
> +        var hoursPerWeek: Int = -1
Why `-1`?

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/HpiCourseDetailPageCrawler.kt
> +                    // TODO: search for teletask links
Should be moved to a new issue or just deleted

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/HpiCourseDetailPageCrawler.kt
> +        if(string.isBlank())
This line doesn't seem to be properly formatted

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/HpiCourseDetailPageCrawler.kt
> +            }
Exceptions shouldn't be silently ignored - at least add a comment explaining the reason

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/Main.kt
> +const val NAME = "HPI-MobileDev-Crawler[Courses]"
Should be the singular "course"

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/Main.kt
> +val requestCount = AtomicInteger(0)
Can be a simple Int

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/Main.kt
> +            }
Don't silently ignore exceptions, at least add a comment

2019-10-06 18:04 UTC, JonasWanke commented on service-course-crawler/src/main/kotlin/de/hpi/cloud/course/crawler/Main.kt
> +            }
Don't silently ignore exceptions, at least add a comment

2019-10-07 08:03 UTC, JonasWanke approved these changes

2019-10-07 08:03 UTC, merged