Issue/35 iso instant format
HPI-de/hpi-cloud pull request #64
Opened 2020-01-24 19:50 UTC by ShirleyNekoDev

**Fixes: #35 **

**Checklist**

- [x] Commit messages follow conventionalcommits.org
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Changes**

- instants now serialize to ISO-format
- proto and json serialization has been moved to respective package
- removed source from entity
- fixed build scripts for each service
- moved news-crawler package to news-service
- fixed news-crawler

2020-01-24 21:21 UTC, JonasWanke requested changes

2020-01-24 21:21 UTC, JonasWanke commented on common/src/main/kotlin/de/hpi/cloud/common/Context.kt
> +        )
As I understand it, this method is used by our crawlers—or at least not by gRPC services. Maybe we can find a different name like `forCrawler`/`forInternal`?

2020-01-24 21:21 UTC, JonasWanke commented on common/src/main/kotlin/de/hpi/cloud/common/couchbase/Document.kt
> +}
Can this function be private?

2020-01-24 21:21 UTC, JonasWanke commented on common/src/main/kotlin/de/hpi/cloud/common/utils/Image.kt
> +}
This should be defined in `de.hpi.cloud.common.types.Image.kt` itself

2020-01-24 21:21 UTC, JonasWanke commented on common/src/main/kotlin/de/hpi/cloud/common/utils/L10n.kt
> +    get() = maxBy { it.weight }?.range?.parseLocale() ?: LOCALE_FALLBACK
This should be moved to `de.hpi.cloud.common.types.L10n.kt`

2020-01-24 21:21 UTC, JonasWanke commented on service-news-crawler/build.gradle
> +    mainClassName = "crawler.MainKt"
We no longer need this file.

2020-01-24 21:21 UTC, JonasWanke commented on service-news/src/main/kotlin/crawler/ArticleCrawler.kt
> +package crawler
The news crawler should reside in the package `de.hpi.cloud.news.crawlers`

2020-01-24 21:21 UTC, JonasWanke commented on service-news/src/main/kotlin/crawler/ArticlePreview.kt
> +        val dateString = SORTABLE_DATE_FORMAT.format(publishedAt.atZone(ZoneId.systemDefault()))
We don't want to use the time zone of our server, but `Europe/Berlin` as the location of the HPI.

2020-01-24 21:21 UTC, JonasWanke commented on service-news/src/main/kotlin/crawler/HpiMediaArchive.kt
> +            .atZone(ZoneId.of("Europe/Berlin"))
Zone could be a constant

2020-01-24 21:21 UTC, JonasWanke commented on service-news/src/main/kotlin/crawler/Main.kt
> +import de.hpi.cloud.common.couchbase.toJsonDocument
Unused import

2020-01-24 21:21 UTC, JonasWanke commented on common/src/main/kotlin/de/hpi/cloud/common/types/Instant.kt
> +}
We should be able to get rid of this class

2020-01-24 21:21 UTC, JonasWanke commented on common/src/main/kotlin/de/hpi/cloud/common/utils/Instant.kt
> +fun Instant.toIsoString() = DateTimeFormatter.ISO_INSTANT.format(this)
We can rename this file to `DateTime`  so it can also contain other related extensions

2020-01-24 21:47 UTC, ShirleyNekoDev commented on common/src/main/kotlin/de/hpi/cloud/common/couchbase/Document.kt
> +}
inline usage requires public extension method

2020-01-25 15:13 UTC, JonasWanke commented on common/src/main/kotlin/de/hpi/cloud/common/serializers/ProtoSerializer.kt
> +}
Why not move it into the `serializers.proto` package?

2020-02-06 18:41 UTC, JonasWanke approved these changes

2020-02-06 18:41 UTC, merged